# Generated by Django 5.2.7 on 2025-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0003_blogpost_slug_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoImage', models.ImageField(default='samurai.jpeg', upload_to='logo_images/')),
            ],
        ),
    ]
