# Generated by Django 5.2.7 on 2025-10-20 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0003_remove_supporter_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bugReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('reports', models.CharField(default=' whatchu learning...?', max_length=300)),
                ('title', models.CharField(default='titleHead', max_length=100)),
                ('poc_image', models.ImageField(default='nopic.jpg', upload_to='bug_pics/')),
            ],
        ),
        migrations.DeleteModel(
            name='SpecializationReports',
        ),
    ]
