# Generated by Django 5.2.7 on 2025-10-21 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0004_bugreports_delete_specializationreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='is_staff',
        ),
    ]
