# Generated by Django 5.2.7 on 2025-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0004_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='key',
            field=models.CharField(default='default_key', max_length=100, unique=True),
        ),
    ]
