# Generated by Django 5.2.7 on 2025-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0005_remove_supporter_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supporter',
            name='alias',
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
