# Generated by Django 5.2.7 on 2025-10-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0005_defaults_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='value',
            field=models.CharField(default='default_value', max_length=255),
        ),
    ]
