# Generated by Django 5.2.7 on 2025-10-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0006_defaults_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaults',
            name='key',
        ),
        migrations.RemoveField(
            model_name='defaults',
            name='value',
        ),
        migrations.AlterField(
            model_name='defaults',
            name='logoImage',
            field=models.ImageField(default='samurai.jpeg', upload_to=''),
        ),
    ]
