# Generated by Django 5.2.7 on 2025-10-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0006_remove_supporter_alias_supporter_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
