# Generated by Django 5.2.7 on 2025-10-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0007_remove_defaults_key_remove_defaults_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaults',
            name='logoImage',
            field=models.ImageField(default='samurai.jpeg', upload_to='default_images/', verbose_name='samurai.jpeg'),
        ),
    ]
