# Generated by Django 5.2.7 on 2025-10-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0007_supporter_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporter',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
    ]
