# Generated by Django 5.2.7 on 2025-10-30 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0008_alter_defaults_logoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaults',
            name='logoImageName',
            field=models.CharField(default='samurai.jpeg', max_length=100),
        ),
    ]
