# Generated by Django 5.2.7 on 2025-10-30 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0011_remove_blogpost_category_blogpost_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='categoryClass',
        ),
    ]
