# Generated by Django 5.2.7 on 2025-10-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0012_rename_name_category_categoryclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='posts', to='c3App.category'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
