# Generated by Django 5.2.7 on 2025-10-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c3App', '0013_alter_blogpost_category_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='c3App.category'),
        ),
    ]
