"""
Django settings for c3 project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys
import os
import logging
from configurations import Configuration, values

logger=logging.getLogger(# In the context of the Django settings file you provided, `__name__` refers
# to the name of the current module. When used in the line
# `logger=logging.getLogger(__name__)`, it is used to create a logger object
# specific to the current module.
__name__)


class DevMode(Configuration):

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent


    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'django-insecure-fw0gc!b7jjgloxwg)-6(#s8_%3e#mxx-0o8!nu*d9^4^#$8oht'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = values.ListValue(["localhost", "0.0.0.0"])
            #PARSING conf-vars

            #bool vars,secretvals,
            #NOTE:FALSE not 'false' or '0' are considered True---
            #for secret vals, if not found, a random one is generated and used.
            #####otherwise,SECRET_KEY=values.SecretValue(),not.secretval('default_key_here')
            #SO WHERE IS THE VALUE STORED? ENV VARIABLES OR A .env FILE. example for secret key:
            #export DJANGO_SECRET_KEY='your_secret_key_here'
            # List values to make appendlist arrays easier i.e the allowed hosts variable.
            #for db_values:import dj_database_url, db_schema,
            #






    # Application definition

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'c3App',
        'rest_framework',
        ###'django_filters',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'c3.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'c3.wsgi.application'


    # Database
    # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


    # Password validation
    # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]
    #AUTH_USER_MODEL = 'c3App.Supporter'

    # Internationalization
    # https://docs.djangoproject.com/en/5.2/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_TZ = True


    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/5.2/howto/static-files/

    STATIC_URL = 'static/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


    #logging can be done anywhere in the code since logging import is globally accessible.
    #best done in the settings .py: centralizing configs,clean and logging at startup.
    Logging={
        'version':1,
        'disable_existing_loggers':False,
        'handlers':{
            'console':{
                'class':'logging.StreamHandler',
                'stream':sys.stdout,

            },
            },

        "root":{
            'handlers':['console'],
            'level':'DEBUG',
        },


    }

class Prod(DevMode):

    DEBUG = False
